[build]
builder = "dockerfile"
dockerfilePath = "packages/api/Dockerfile"

[deploy]
startCommand = "npx prisma@5.22.0 db push --schema=./prisma/schema.prisma --skip-generate && node dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
